name: patients
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  states_rebuilder: ^6.3.0
  path_provider: ^2.1.1
  flex_color_scheme: ^7.3.1
  uuid: ^4.1.0
  colornames: ^0.1.0
  hive_flutter: 
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  json_annotation: 4.8.1
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Lotion
      fonts:
        - asset: assets/Lotion-Black.ttf
        - asset: assets/Lotion-BlackItalic.ttf
          style: italic
        - asset: assets/Lotion-Bold.ttf
        - asset: assets/Lotion-BoldItalic.ttf
          style: italic
        - asset: assets/Lotion-Regular.ttf
        - asset: assets/Lotion-RegularItalic.ttf
          style: italic
        - asset: assets/Lotion-SemiBold.ttf
        - asset: assets/Lotion-SemiBoldItalic.ttf
          style: italic
    - family: Cascadia Code
      fonts:
        - asset: assets/Cascadia.ttf
          

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/examination.png"
  remove_alpha_ios: true
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/examination.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/examination.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/examination.png"
# dart run flutter_launcher_icons